name: DGP Clean Start

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print messages
        run: |
          echo "🔥 DGP SYSTEM STARTED"
          echo "LEVEL 1 OK"
          echo "LEVEL 2 OK"
          echo "LEVEL 3 OK"
          echo "ALL GOOD"
